---
- name: Install packages
  yum: name={{ item }} state=present
  with_items:
      - epel-release

- name: Install nginx
  yum: 
    name: nginx
    state: present
    update_cache: yes

- name: Restart nginx
  systemd: 
    name: nginx
    state: restarted
    enabled: yes
